doctrine:
    dbal: { connections: { default: { host: localhost, port: 3306, user: root, password: root, dbname: Mydemo, mapping_types: { enum: string, bit: boolean }, server_version: 8.0.29-0ubuntu0.20.04.3 } } }
 #db
