doctrine:
    dbal: { connections: { default: { host: database-1.c2iubwxfmyim.us-east-1.rds.amazonaws.com, port: 3306, user: admin, password: root1234, dbname: Mydemo, mapping_types: { enum: string, bit: boolean }, server_version: 2.3:o:amazon:amazon_linux:2 } } }
 #db
